import { Award, Code, Users } from "lucide-react";

export const communities = [
  "Giveth",
  "Pairwise",
  "Alchemy",
  "Encode Club",
  "Lens Protocol",
];

export const timelineEvents = [
  {
    id: 2,
    year: "Apr, 2024",
    title: "ETHGlobal Hackathon",
    company: "ETHGlobal",
    type: "achievement",
    description: "Built a AI-powered trading bot",
    tech: [
      "Solidity",
      "Typescript",
      "Next.js",
      "Vercel",
      "PostgreSQL",
      "Drizzle",
    ],
    icon: Award,
  },
  {
    id: 4,
    year: "Feb, 2025 - Present",
    title: "Tech Talk",
    company: "Geeks Blabla",
    type: "community",
    description: "Presented on 'Overcoming the N+1 problem'",
    tech: ["Public Speaking", "Engineering", "Frontend"],
    icon: Users,
  },
  {
    id: 1,
    year: "Apr, 2024",
    title: "Mid Software Engineer",
    company: "General Magic",
    type: "work",
    description:
      "Working on Giveth, Pairwise, and WorldView Quadratic voting World Mini-App",
    tech: [
      "TypeScript",
      "React",
      "Node.js",
      "Next.js",
      "Nest.js",
      "TailwindCSS",
      "viem",
      "wagmi",
      "Solidity",
      "PostgreSQL",
      "Drizzle",
      "Vercel",
      "AWS",
      "CI/CD",
      "Docker",
    ],
    icon: Code,
  },
  {
    id: 3,
    year: "Apr, 2023",
    title: "Frontend Developer",
    company: "V12 Software",
    type: "work",
    description: "Worked on a Car Dealearship platform",
    tech: ["Vue.js", "Vuex", "CI/CD", "AWS", "Docker"],
    icon: Code,
  },
  {
    id: 5,
    year: "2022",
    title: "Full-stack Developer",
    company: "Mamane.Tech",
    type: "work",
    description: "Built various web apps for clients",
    tech: [
      "React",
      "Node.js",
      "Next.js",
      "MySQL",
      "Prisma",
      "tRPC",
      "CI/CD",
      "Docker",
      "AWS",
    ],
    icon: Code,
  },
  {
    id: 6,
    year: "2021",
    title: "Full-stack Developer",
    company: "Big M Solutions",
    type: "work",
    description: "Built a web app for a client",
    tech: [
      "Node.js",
      "Express",
      "MongoDB",
      "Vue.js",
      "ArangoDB",
      "Docker",
      "Nginx",
    ],
    icon: Code,
  },
];
